title:   Thomas Chan
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Perceptive and logical professional with ability to communicate with all parties. Good at seeing the bigger picture of a task, while also paying attention to the fine details. Able to learn and adapt to the nuances of all businesses.
  <br><br>
  <a href="https://www.linkedin.com/in/thomas-chan-b564b4231/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://public.tableau.com/app/profile/thomas.chan4164">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/thomaschan">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal 
 
